// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (PaymentAccount, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (PaymentAccount, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (PaymentEntry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (PaymentTransfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (PaymentAccount, error)
	GetAccountForUpdate(ctx context.Context, id int64) (PaymentAccount, error)
	GetEntry(ctx context.Context, id int64) (PaymentEntry, error)
	GetTransfer(ctx context.Context, id int64) (PaymentTransfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]PaymentAccount, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]PaymentEntry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]PaymentTransfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (PaymentAccount, error)
}

var _ Querier = (*Queries)(nil)
